### ISSUE TITLE
[Hive][v0.1.44]The app crashes after granting permission.

### ISSUE THREAD

**Issue by masudr4n4** [gpetuhov/Hive#1]
<h4>Actual behavior</h4>
The app want permission first when open the app.I click GRANT PERMISSION,app crashes immiedieatly
<h4>Expected behavior</h4>
Expected that i can use the app without any error.
<h4>How to reproduce</h4>
<ol>
<li>Install the apps and open the app</li>
<li>click GRANT PERMISSION</li>
<li>see the error</li>
</ol>
<h4>Information</h4>
<ul>
<li>App version:V0.1.44</li>
<li>OS:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/gS8kPALfZVU">https://youtu.be/gS8kPALfZVU</a>
<h4>Logcat</h4>
<pre><code>
05-15 07:47:12.330  4731  4851 E AndroidRuntime: FATAL EXCEPTION: Thread-17
05-15 07:47:12.330  4731  4851 E AndroidRuntime: Process: com.gpetuhov.android.hive, PID: 4731
05-15 07:47:12.330  4731  4851 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
05-15 07:47:12.330  4731  4851 E AndroidRuntime: 	at gu.b(:com.google.android.gms.dynamite_mapsdynamite@17122077@17.1.22 (100300-245988633):3)
05-15 07:47:12.330  4731  4851 E AndroidRuntime: 	at gr.a(:com.google.android.gms.dynamite_mapsdynamite@17122077@17.1.22 (100300-245988633):3)
05-15 07:47:12.330  4731  4851 E AndroidRuntime: 	at gt.a(:com.google.android.gms.dynamite_mapsdynamite@17122077@17.1.22 (100300-245988633):14)
05-15 07:47:12.330  4731  4851 E AndroidRuntime: 	at com.google.maps.api.android.lib6.drd.ak.a(:com.google.android.gms.dynamite_mapsdynamite@17122077@17.1.22 (100300-245988633):4)
05-15 07:47:12.330  4731  4851 E AndroidRuntime: 	at fv.a(:com.google.android.gms.dynamite_mapsdynamite@17122077@17.1.22 (100300-245988633):22)
05-15 07:47:12.330  4731  4851 E AndroidRuntime: 	at fv.run(:com.google.android.gms.dynamite_mapsdynamite@17122077@17.1.22 (100300-245988633):8)
05-15 07:47:12.330  4731  4851 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/00000018/MapsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/00000018/MapsDynamite.apk!/lib/armeabi-v7a, /data/user_de/0/com.google.android.gms/app_chimera/m/00000018/MapsDynamite.apk!/lib/armeabi, /system/lib]]
05-15 07:47:12.330  4731  4851 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
05-15 07:47:12.330  4731  4851 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
05-15 07:47:12.330  4731  4851 E AndroidRuntime: 	at ab.loadClass(:com.google.android.gms.dynamite_dynamiteloader@17122077@17.1.22 (100300-245988633):4)
05-15 07:47:12.330  4731  4851 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-15 07:47:12.330  4731  4851 E AndroidRuntime: 	... 6 more
</code>
</pre>

**Comment by maaudrana** [comment]
@gpetuhov  dear can you chack the issue?

**Comment by gpetuhov** [comment]
@maaudrana Thanks for the issue! I've updated beta with new features and bug fixes. Please check new app version 0.1.46 as soon as changes are published on Google Play: https://play.google.com/apps/testing/com.gpetuhov.android.hive

**Comment by gpetuhov** [comment]
@maaudrana New app version is available on Google Play: https://play.google.com/apps/testing/com.gpetuhov.android.hive

**Comment by masudr4n4** [comment]
Thanks it working fine now.
