### ISSUE TITLE
BUG found in Hive app The application crashes when I try to change the profile picture

### ISSUE THREAD

**Issue by saraji-ali** [gpetuhov/Hive#3]
# Project Information

* Repository:  https://github.com/gpetuhov/Hive
* Project Name:  Hive

# Expected behavior

The profile picture should change when I try to change the profile picture. And the selected new picture should appear on the profile

# Actual behavior

After going to profile The application crashes when I try to change the profile picture

# How to reproduce
1-[Download ](https://play.google.com/store/apps/details?id=com.gpetuhov.android.hive&ah=mg3ZMk3XOh7ku1YRv9uagzRmaMw)the app and open it
2- click GRANT PERMISSION
3- click on the  profile 
4-Try changing the profile picture
5- see bug 

* Browser/App version:  0.1.46
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug
![20190514_215928](https://user-images.githubusercontent.com/50115498/57718150-88140800-7631-11e9-8aeb-5863c06bb36d.gif)

# My Github Account
https://github.com/facebook-786

# Logcat

<pre><code>E/AndroidRuntime(20945): FATAL EXCEPTION: DefaultDispatcher-worker-1

E/AndroidRuntime(20945): Process: com.gpetuhov.android.hive, PID: 20945

E/AndroidRuntime(20945): java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()

E/AndroidRuntime(20945): 	at android.os.Handler.<init>(Handler.java:200)

E/AndroidRuntime(20945): 	at android.os.Handler.<init>(Handler.java:114)

E/AndroidRuntime(20945): 	at android.widget.Toast$TN.<init>(Toast.java:569)

E/AndroidRuntime(20945): 	at android.widget.Toast.<init>(Toast.java:129)

E/AndroidRuntime(20945): 	at android.widget.Toast.makeText(Toast.java:427)

E/AndroidRuntime(20945): 	at com.gpetuhov.android.hive.ui.fragment.ProfileFragment.showToast(ProfileFragment.kt:584)

E/AndroidRuntime(20945): 	at com.gpetuhov.android.hive.presentation.view.ProfileFragmentView$$State.showToast(ProfileFragmentView$$State.java:790)

E/AndroidRuntime(20945): 	at com.gpetuhov.android.hive.presentation.presenter.ProfileFragmentPresenter.showToast(ProfileFragmentPresenter.kt:552)

E/AndroidRuntime(20945): 	at com.gpetuhov.android.hive.presentation.presenter.ProfileFragmentPresenter.access$showToast(ProfileFragmentPresenter.kt:21)

E/AndroidRuntime(20945): 	at com.gpetuhov.android.hive.presentation.presenter.ProfileFragmentPresenter$changeUserPic$1.invoke(ProfileFragmentPresenter.kt:209)

E/AndroidRuntime(20945): 	at com.gpetuhov.android.hive.presentation.presenter.ProfileFragmentPresenter$changeUserPic$1.invoke(ProfileFragmentPresenter.kt:21)

E/AndroidRuntime(20945): 	at com.gpetuhov.android.hive.repository.Repository$uploadImage$1.invokeSuspend(Repository.kt:1703)

E/AndroidRuntime(20945): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

E/AndroidRuntime(20945): 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)

E/AndroidRuntime(20945): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)

E/AndroidRuntime(20945): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)

E/AndroidRuntime(20945): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

</code></pre>

**Comment by gpetuhov** [comment]
@facebook-786 Thank you for testing! Working on this.

**Comment by gpetuhov** [comment]
@facebook-786 The reason was trying to show image upload error message on background thread, which caused the application to crash. Please check new app version 0.1.47 with bug fixes: https://play.google.com/apps/testing/com.gpetuhov.android.hive

**Comment by gpetuhov** [comment]
Closing, because the reason is the same as here: https://github.com/gpetuhov/Hive/issues/7

**Comment by XAMIR555** [comment]
thanks Sir All the bugs has been solved
