### ISSUE TITLE
The app crashes when click back in privacy policy page

### ISSUE THREAD

**Issue by lushohammy** [gpetuhov/Hive#4]
#### Expected behavior
user should be able to read the privacy policy page in rotate mode and back smoothly when they click on back icon.

#### Actual behavior
when i rotate my device and read privacy Policy and click on back button on the privacy Policy page the app crashed

#### How to reproduce
* download the app
* open it and go to the privacy Policy page
* now rotate your device ,continue reading and click the back button with rotate screen
* and see the bug

#### Operating system 
* App version:v 0.1.46
* Android v8.1.0 OPMI

#### Recording Of The Bug
https://www.youtube.com/watch?v=8HqBh-u2orw&feature=youtu.be&fbclid=IwAR1wTcjJJxbX1l3MrWdKczrc-nyePa_NbI0jyffAUh_Ori4nYCNR_edSGPY

**Comment by gpetuhov** [comment]
@lushohammy Thank you for finding new bug! I'll see what's the reason.

**Comment by lushohammy** [comment]
thanks sir

**Comment by gpetuhov** [comment]
@lushohammy Please check new app version 0.1.47 with bug fixes: https://play.google.com/apps/testing/com.gpetuhov.android.hive
