### ISSUE TITLE
[Hive][v0.1.46]The app crashes when trying  to sign in with old accounts. 

### ISSUE THREAD

**Issue by masudr4n4** [gpetuhov/Hive#5]
<h4>Actual behavior</h4>
I can not sign in with my old account which was created past.
<h4>Expected behavior</h4>
Expected that i can sign in and use app without crash.
<h4>How to reproduce</h4>
<ol>
<li>Install the apps and open the app</li>
<li>click GRANT PERMISSION</li>
<li>click sign in with email</li>
<li> give mail and password </li>
<li>Click sign</li>
<li>See error</li>
</ol>
<h4>Information</h4>
<ul>
<li>App version:V0.1.46</li>
<li>OS:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/sw_bLZ2IBxU">https://youtu.be/sw_bLZ2IBxU</a>
<h4>Logcat</h4>
<pre>
<code>
05-15 09:09:30.723 7578 7578 E AndroidRuntime: FATAL EXCEPTION: main 
05-15 09:09:30.723 7578 7578 E AndroidRuntime: Process: com.gpetuhov.android.hive, PID: 7578 05-15 09:09:30.723 7578 7578 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.gpetuhov.android.hive.service.LocationService: java.lang.SecurityException: Permission Denial: startForeground from pid=7578, uid=10239 requires android.permission.FOREGROUND_SERVICE 
05-15 09:09:30.723 7578 7578 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3769) 
05-15 09:09:30.723 7578 7578 E AndroidRuntime: 	at android.app.ActivityThread.access$1400(ActivityThread.java:237) 
05-15 09:09:30.723 7578 7578 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
05-15 09:09:30.723 7578 7578 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
 05-15 09:09:30.723 7578 7578 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214) 05-15 09:09:30.723 7578 7578 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073) 
05-15 09:09:30.723 7578 7578 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method) 05-15 09:09:30.723 7578 7578 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
05-15 09:09:30.723 7578 7578 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
 05-15 09:09:30.723 7578 7578 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: startForeground from pid=7578, uid=10239 requires android.permission.FOREGROUND_SERVICE
 05-15 09:09:30.723 7578 7578 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:1966) 
05-15 09:09:30.723 7578 7578 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1934)
 05-15 09:09:30.723 7578 7578 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1884)
 05-15 09:09:30.723 7578 7578 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5043) 
05-15 09:09:30.723 7578 7578 E AndroidRuntime: 	at android.app.Service.startForeground(Service.java:695) 
05-15 09:09:30.723 7578 7578 E AndroidRuntime: 	at com.gpetuhov.android.hive.service.LocationService.startForegroundService(LocationService.kt:55) 05-15 09:09:30.723 7578 7578 E AndroidRuntime: 	at com.gpetuhov.android.hive.service.LocationService.onCreate(LocationService.kt:34) 
05-15 09:09:30.723 7578 7578 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3757) 
05-15 09:09:30.723 7578 7578 E AndroidRuntime: 	... 8 more
</code>
</pre>

**Comment by gpetuhov** [comment]
@maaudrana Thanks for finding this! I'll see what causes the exception.

**Comment by gpetuhov** [comment]
@maaudrana Please check new app version 0.1.47 with bug fixes: https://play.google.com/apps/testing/com.gpetuhov.android.hive
