### ISSUE TITLE
[Hive][v0.1.46]The app crashes when trying  to add an offer.

### ISSUE THREAD

**Issue by masudr4n4** [gpetuhov/Hive#6]
<h4>Actual behavior</h4>
The app crashes if i click save button to save an offer.
<h4>Expected behavior</h4>
Expected that i can save an offer from the app successfully without crash..
<h4>How to reproduce</h4>
<ol>
<li>Install the apps and open the app</li>
<li>Click profile</li>
<li>Scroll down and click Add offer.</li>
<li> Add a title ,add a description </li>
<li>click add photo ,choose any photo from gallery</li>
<li>wait for upload the photo then save icon.</li>
<li>See the error.</>
</ol>
<h4>Information</h4>
<ul>
<li>App version:V0.1.46</li>
<li>OS:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/j4uEmLab6_A">https://youtu.be/j4uEmLab6_ABxU</a>
<h4>LogCat</h4>
<pre><code>
05-15 09:11:54.428 10199 10199 E AndroidRuntime: FATAL EXCEPTION: main
05-15 09:11:54.428 10199 10199 E AndroidRuntime: Process: com.gpetuhov.android.hive, PID: 10199
05-15 09:11:54.428 10199 10199 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.gpetuhov.android.hive.service.LocationService: java.lang.SecurityException: Permission Denial: startForeground from pid=10199, uid=10239 requires android.permission.FOREGROUND_SERVICE
05-15 09:11:54.428 10199 10199 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3769)
05-15 09:11:54.428 10199 10199 E AndroidRuntime: 	at android.app.ActivityThread.access$1400(ActivityThread.java:237)
05-15 09:11:54.428 10199 10199 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
05-15 09:11:54.428 10199 10199 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-15 09:11:54.428 10199 10199 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-15 09:11:54.428 10199 10199 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
05-15 09:11:54.428 10199 10199 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-15 09:11:54.428 10199 10199 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-15 09:11:54.428 10199 10199 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
05-15 09:11:54.428 10199 10199 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: startForeground from pid=10199, uid=10239 requires android.permission.FOREGROUND_SERVICE
05-15 09:11:54.428 10199 10199 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:1966)
05-15 09:11:54.428 10199 10199 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1934)
05-15 09:11:54.428 10199 10199 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1884)
05-15 09:11:54.428 10199 10199 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5043)
05-15 09:11:54.428 10199 10199 E AndroidRuntime: 	at android.app.Service.startForeground(Service.java:695)
05-15 09:11:54.428 10199 10199 E AndroidRuntime: 	at com.gpetuhov.android.hive.service.LocationService.startForegroundService(LocationService.kt:55)
05-15 09:11:54.428 10199 10199 E AndroidRuntime: 	at com.gpetuhov.android.hive.service.LocationService.onCreate(LocationService.kt:34)
05-15 09:11:54.428 10199 10199 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3757)
05-15 09:11:54.428 10199 10199 E AndroidRuntime: 	... 8 more
</code>
</pre>

**Comment by gpetuhov** [comment]
@maaudrana Thank you for finding this one! I'll see what I can do.

**Comment by gpetuhov** [comment]
@maaudrana Please check new app version 0.1.47 with bug fixes: https://play.google.com/apps/testing/com.gpetuhov.android.hive
