### ISSUE TITLE
BUG found in Hive app The application crashes inside the offer tab when I add a picture

### ISSUE THREAD

**Issue by saraji-ali** [gpetuhov/Hive#7]
# Project Information

* Repository: https://github.com/gpetuhov/Hive
* Project Name: Hive

# Expected behavior

When I try to add a picture to the offer tab, the picture should be added to the offer tab And the picture in the offer tab should appear above the top

# Actual behavior

The application crashes inside the offer tab when I add a picture

# How to reproduce

1-[Download ](https://play.google.com/store/apps/details?id=com.gpetuhov.android.hive&ah=mg3ZMk3XOh7ku1YRv9uagzRmaMw)the app and open it
2- click GRANT PERMISSION
3- click on the  profile 
4- click on Add Offer 
5- click on Add photo  Try to uploading any picture
6- see bug 

* Browser/App version:  0.1.46
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug
![20190515_160226](https://user-images.githubusercontent.com/50115498/57771694-513d0100-76c8-11e9-8dd7-e7bbf673aaf9.gif)

# My Github Account
https://github.com/facebook-786

# Beneficiaries
* @utopian.pay = %5

# Logcat

<pre><code>E/AndroidRuntime(14100): FATAL EXCEPTION: DefaultDispatcher-worker-1

E/AndroidRuntime(14100): Process: com.gpetuhov.android.hive, PID: 14100

E/AndroidRuntime(14100): java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()

E/AndroidRuntime(14100): 	at android.os.Handler.<init>(Handler.java:200)

E/AndroidRuntime(14100): 	at android.os.Handler.<init>(Handler.java:114)

E/AndroidRuntime(14100): 	at android.widget.Toast$TN.<init>(Toast.java:569)

E/AndroidRuntime(14100): 	at android.widget.Toast.<init>(Toast.java:129)

E/AndroidRuntime(14100): 	at android.widget.Toast.makeText(Toast.java:427)

E/AndroidRuntime(14100): 	at com.gpetuhov.android.hive.ui.fragment.UpdateOfferFragment.showToast(UpdateOfferFragment.kt:344)

E/AndroidRuntime(14100): 	at com.gpetuhov.android.hive.presentation.view.UpdateOfferFragmentView$$State.showToast(UpdateOfferFragmentView$$State.java:358)

E/AndroidRuntime(14100): 	at com.gpetuhov.android.hive.presentation.presenter.UpdateOfferFragmentPresenter.showToast(UpdateOfferFragmentPresenter.kt:326)

E/AndroidRuntime(14100): 	at com.gpetuhov.android.hive.presentation.presenter.UpdateOfferFragmentPresenter.access$showToast(UpdateOfferFragmentPresenter.kt:19)

E/AndroidRuntime(14100): 	at com.gpetuhov.android.hive.presentation.presenter.UpdateOfferFragmentPresenter$addPhoto$2.invoke(UpdateOfferFragmentPresenter.kt:272)

E/AndroidRuntime(14100): 	at com.gpetuhov.android.hive.presentation.presenter.UpdateOfferFragmentPresenter$addPhoto$2.invoke(UpdateOfferFragmentPresenter.kt:19)

E/AndroidRuntime(14100): 	at com.gpetuhov.android.hive.repository.Repository$uploadImage$1.invokeSuspend(Repository.kt:1703)

E/AndroidRuntime(14100): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

E/AndroidRuntime(14100): 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)

E/AndroidRuntime(14100): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)

E/AndroidRuntime(14100): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)

E/AndroidRuntime(14100): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Wor
</code></pre>

**Comment by gpetuhov** [comment]
@facebook-786 Thank you for the issue! Working on it.

**Comment by gpetuhov** [comment]
@facebook-786 The reason was trying to show image upload error message on background thread, which caused the application to crash. Please check new app version 0.1.47 with bug fixes: https://play.google.com/apps/testing/com.gpetuhov.android.hive

**Comment by saraji-ali** [comment]
thank you, sir, now the bug has been fixed in latest version 0.1.47

**Comment by gpetuhov** [comment]
> thank you, sir, now the bug has been fixed in latest version 0.1.47

@facebook-786 Glad to hear that! Thanks for testing!
